package:
  name: anaconda_powershell_prompt
  version: 1.1.0

build:
  number: 0
  skip: True  # [not win]

requirements:
  run_constrained:
    - anaconda-navigator >=1.9.8
    - menuinst >=2.1.0

test:
  commands:
    - IF NOT EXIST %PREFIX%\\Menu\\anaconda_powershell_prompt_menu.json EXIT 1
    - IF NOT EXIST %PREFIX%\\Menu\\anaconda_powershell_prompt.ico EXIT 1

app:
  entry: for /D %%i in ("${CONDA_ROOT_PREFIX}") do wt -w last new-tab -p "Anaconda PowerShell Prompt (%%~ni)"
  summary: Opens a PowerShell instance with conda activated (requires menuinst 2.1.1 or greater).
  icon: anaconda_powershell_prompt.png
  type: desk

about:
  description: |
    Package to create shortcuts for PowerShell with an activated conda environment.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: PowerShell shortcut creator for Anaconda
  home: https://github.com/AnacondaRecipes/anaconda_powershell_prompt-feedstock
  dev_url: https://github.com/AnacondaRecipes/anaconda_powershell_prompt-feedstock
  doc_url: https://github.com/AnacondaRecipes/anaconda_powershell_prompt-feedstock/blob/main/README.md

extra:
  recipe-maintainers:
    - marcoesters
